### ISSUE TITLE
airqualityES - rostemplate project

### ISSUE THREAD

**Issue by dieghernan** [rOpenSpain/airqualityES#1]
https://github.com/orgs/rOpenSpain/projects

Dear developers,

I have created a fork including the deploy of your package on your gh-pages branch using the rostemplate (see Slack channel and https://ropenspain.github.io/rostemplate/). See a live preview of your `pkgdown` site here:
https://dieghernan.github.io/airqualityES/

An additional GitHub Action `check-standard.yaml` has been included. That action would check your package (AS CRAN) on several platforms on every push, pull request and every first day of the month. The goal is to provide CI on your package.

## Actions on your package:

- Check locally and rebuild documentation (upgrade Roxygen version)

- Small fix on README. Now your package name is h1 instead of h2.

- Implementation of github-actions and related .gitgnore and .Rbuildignore

## Next steps
 You should receive a Pull Request with these modifications.

After your review and in case you consider merging, consider to deploy Github Pages on your settings (gh-pages branch).

Once it is done, I would appreciate if you move this issue to the Deployed tab on the [Project panel](https://github.com/orgs/rOpenSpain/projects) (see also Projects tab on this website).

---
LOG

- @dieghernan reviewing
- @jdieramon owner

Fork: https://github.com/dieghernan/airqualityES

Live preview: https://dieghernan.github.io/airqualityES/

TODO: Open issue and pull request. Final deployment up to repo owners

**Comment by dieghernan** [comment]
Hi @jdieramon, just a quick question. Did you enable GitHub pages on this repository? The new website won’t be deployed until this is done. You can go to Settings> GitHub pages and enable it for the branch gh-pages.

Regards

**Comment by jdieramon** [comment]
Hi @dieghernan . The site is ready to be published at https://ropenspain.github.io/airqualityES/ 
Is it OK now ?

**Comment by dieghernan** [comment]
Fantastic! Thank you very much
